services:
  devcontainer:
    build: 
      context: ./.devcontainer
      dockerfile: Dockerfile

    volumes:
      - ..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
  mysql:
    container_name: mysql
    image: mysql:8.4
    volumes:
      - application-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: application_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    driver: bridge

volumes:
  application-mysql-data: